### ISSUE TITLE
Использование Windows сервера

### ISSUE THREAD

**Issue by VadVergasov** [SlavikMIPT/tgcloud#9]
Можно ли как-то сие чудо запустить на Windows 10? Попробовал подсистему Ubuntu - не работает FUSE, как и на Windows не могу найти необходимых софтин (Нашел winfsp и Docan). Дошел до ошибки именно с FUSE: 

```
Error: The Python FUSE binding isn't installed!
If you're on Ubuntu try running `sudo apt-get install python-fuse'.
```
Что делать? Просто не очень очеться разворачивать виртулаку ради такого....

**Comment by SlavikMIPT** [comment]
ну я запускаю на VDS на linux и через sftp клиент подключаюсь, на windows пока прокидывать не пробовал - в итоге нужно будет нативно написать драйвер. На данный момент либо через sftp клиент + удаленная VDS на линуксе, либо виртуалка... 
Попробовал на wsl запустить
```
modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.4.0-17134-Microsoft
```
похоже fuse не реализован в wsl
В вашей ошибке написано что fuse для python не установлен, можете попробовать его установить `sudo apt-get install python-fuse`
но скорей всего после установки - при запуске выдаст новую ошибку - сбой инициализации ФС - так как отсутствует модуль fuse

**Comment by VadVergasov** [comment]
Да, на WSL такая же ошибка, и судя по результатам поиска  в WSL нет реализации FUSE.
В общем, надо будет еще посмотреть winfsp с cygwin, может и можно что-то придумать. А пока буду виртуалку творить)

**Comment by SlavikMIPT** [comment]
Решил перевести все на Golang - на данный момент под винду собрал TDLib с Go и Python обертками, https://github.com/dokan-dev/dokany - FUSE API совместимая библиотека для windows для реализации файловых систем, есть также обертки для golang - таким образом можно иметь один и тот же код для linux и windows, при этом использовать golang, при необходимости - python

**Comment by SlavikMIPT** [comment]
P.S. - в windows Insiders уже доступна WSL 2 с прозрачной файловой системой в windows и обратно, там есть fuse, также можно запустить docker демон
